myproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from    boards  import  views
from    accounts    import  views   as  accounts_views
from    django.contrib.auth import  views   as  auth_views

urlpatterns = [
    url(r'^$',  views.home, name='home'),
    url(r'^signup/$',   accounts_views.signup,  name='signup'),
    url(r'^logout/$',   auth_views.LogoutView.as_view(),    name='logout'),
    url(r'^boards/(?P<pk>\d+)/new/$',   views.new_topic,    name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/$',   views.board_topics, name='board_topics'),
    # url(r'^boards/', include('boards.urls')),
    url(r'^admin/', admin.site.urls),

]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

boards/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models  import  User
class Board(models.Model):
    # id = models.AutoField(primary_key=True)          
    name    =   models.CharField(max_length=30, unique=True) 
    description =   models.CharField(max_length=100)
class Topic(models.Model):
    subject =   models.CharField(max_length=255)
    last_updated    =   models.DateTimeField(auto_now_add=True)
    board   =   models.ForeignKey(Board,    related_name='topics')
    starter =   models.ForeignKey(User, related_name='topics')
class Post(models.Model):
    message =   models.TextField(max_length=4000)
    topic   =   models.ForeignKey(Topic,    related_name='posts')
    created_at  =   models.DateTimeField(auto_now_add=True)
    updated_at  =   models.DateTimeField(null=True)
    created_by  =   models.ForeignKey(User, related_name='posts' )
    updated_by  =   models.ForeignKey(User, null=True,  related_name='+')

accounts/forms.py
from    django  import  forms 
from  django.contrib.auth.forms   import  UserCreationForm 
from   django.contrib.auth.models  import  User
class   SignUpForm(UserCreationForm):               
    email   =   forms.CharField(max_length=254, required=True,  widget=forms.EmailInput())          
    class   Meta:                               
        model   =   User                                
        fields  =   ('username',    'email',    'password1',    'password2')

boards/forms.py
# -*- coding: utf-8 -*-
from    django  import  forms 
from  .models import  Topic
class   NewTopicForm(forms.ModelForm):              
    message =   forms.CharField(widget=forms.Textarea(
        attrs={'rows':  5,  'placeholder':  'What   is  on  your    mind?'} 
        ),
     max_length=1000,
     help_text='The  max length  of  the text    is  1000.')
    class   Meta:
        model   =   Topic                               
        fields  =   ['subject', 'message']

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from    django.contrib.auth.forms   import  UserCreationForm 
from    django.contrib.auth import  login   as  auth_login
from    .forms  import  SignUpForm

# Create your views here.
# def signup(request):                
#     # return  render(request, 'signup.html')
#     form    =   UserCreationForm()              
#     return  render(request, 'signup.html',  {'form':    form})

def signup(request):                
    if  request.method  ==  'POST':                             
        form    =   SignUpForm(request.POST)
        if  form.is_valid(): 
            user    =   form.save()  
            auth_login(request, user)   
            return  redirect('home')                
        else:                               
            form    =   SignUpForm()              
        return  render(request, 'signup.html',  {'form': form})

boards/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from    django.contrib.auth.models  import  User 
from django.shortcuts import render, redirect, get_object_or_404 
from .models import Board,Topic,Post
from django.shortcuts import HttpResponse
from django.http import Http404
from    .forms  import  NewTopicForm 
# Create your views here.
def home(request):              
    boards  =   Board.objects.all()  
    return render(request,'home.html',{'boards':boards})           
    # boards_names    =   list()
    # for board in  boards:                             
    #     boards_names.append(board.name)
    # response_html   =   '<br>'.join(boards_names)
    # return  HttpResponse(response_html)

def board_topics(request,   pk):  
    try:
        board   =   Board.objects.get(pk=pk) 
    except Board.DoesNotExist:
        raise Http404  
    return  render(request, 'topics.html',  {'board':   board})

# def new_topic(request,  pk):                
#     board   =   get_object_or_404(Board,    pk=pk) 
#     if  request.method  ==  'POST':                             
#         subject =   request.POST['subject']  
#         message =   request.POST['message']
#         user    =   User.objects.first()
#         topic   =   Topic.objects.create( 
#           subject=subject,    
#           board=board,       
#           starter=user)
#         post    =   Post.objects.create(                
#            message=message,   
#            topic=topic,   
#            created_by=user)
#         return redirect('board_topics',    pk=board.pk)    
#     return  render(request, 'new_topic.html',   {'board':   board} )


def new_topic(request,  pk):                
    board   =   get_object_or_404(Board,    pk=pk)              
    user    =   User.objects.first()        
    #   TODO:   get the currentlylo gged in  user                
    if  request.method  ==  'POST':                             
        form    =   NewTopicForm(request.POST)
        if  form.is_valid():
            topic   =   form.save(commit=False)
            topic.board =   board
            topic.starter   =   user
            topic.save()
            post    =   Post.objects.create(message=form.cleaned_data.get('message'), 
             topic=topic,
             created_by=user)  
            return  redirect('board_topics',    pk=board.pk) 
    else:
        form    =   NewTopicForm()              
    return  render(request, 'new_topic.html',   {'board':   board,  'form': form})

boards/templates/base.html
{%  load    static  %}
<!DOCTYPE html>
 <html>        
 <head>              
 <meta   charset="utf-8">                
 <title>
 {%   block   title   %}
 Django    Boards
 {%    endblock    %}
 </title >           
     <link   rel="stylesheet"    href="{%    static  'css/app.css'   %}">
      <!-- <link   rel="stylesheet"    href="{%    static  'css/accounts.css'   %}"> -->

  <link   rel="stylesheet"    href="{%    static  'css/bootstrap.min.css'    %}">
    {%  block   stylesheet  %}{%    endblock    %}      
          </head>


<body>  
{%  block   body    %}  
 <nav    class="navbar   navbar-expand-lg    navbar-dark bg-dark">
     <div    class="container">
     <a  class="navbar-brand"    href="{%    url 'home'  %}">Django Boards</a> 
      </div>
    <button class="navbar-toggler"  type="button"   data-toggle ="collapse" data-target="#mainMenu" aria-controls="mainMenu"    aria-expanded="false"   aria-label="Toggle  navigation">          
 <span   class="navbar-toggler-icon"></span> 
       </button>      
          <div    class="collapse navbar-collapse"    id="mainMenu"> 
               <ul class="navbar-nav ml-auto">  
            <a  class="nav-link dropdown-toggle"    href="#"    id="userMenu"  data-toggle="dropdown"  aria-haspopup="true"    aria-expa nded="false"> 
 {{  user.username   }}   </a> 
 <div    class="dropdown-menu    dropdown-menu-right"    aria-labelledby="userMenu"> 
               <a  class="dropdown-item"   href="#">My account</a>  
  <a  class="dropdown-item"   href="#">Change password </a>    
     <div    class="dropdown-divider"></div>           
       <a  class="dropdown-item"   href="{%    url 'logout'    %}" >Log    out</a>
  </div>            </li>   </ul>  </div>
   </div> </nav>
  
  
   <div    class="container">           

 <ol class="breadcrumb   my-4">     
 {%  block   breadcrumb  %}                              
 {%  endblock    %}                     
  </ol>     

   {%  block   content %}                   
      {%  endblock    %}             
       </div> 
{% endblock body %}     

<script src="{% static  'js/jquery-3.3.1.min.js'    %}"></script>
<script src="{% static  'js/popper.min.js'  %}"></script>               
<script src="{% static  'js/bootstrap.min.js'   %}"></script>  
       </body> 
       </html>

boards/templates/home.html
{%  extends 'base.html' %}
{%  block   breadcrumb  %}      
<li class="breadcrumb-item  active">Boards</li> 
{%  endblock    %}
{%  block   content %}
<table  border="1" class="table">                  
<thead class="thead-inverse">                          
<tr>                                        
<th>Board</th>                                      
<th>Posts</th>                                      
<th>Topics</th>                                     
<th>Last    Post</th>                               
</tr>                       
</thead>  

<tbody> 
{%  for board   in  boards  %}
<tr>
    <td><a  href="{%    url 'board_topics'  board.pk    %}">{{  board.name }}</a>  <br>   
<small class="text-muted d-block" style="color:#888">{{board.description}}</small>
    </td>
        <td class="align-middle">0</td>                                              
        <td class="align-middle">0</td>                                              
        <td></td>                                       
</tr>
{%  endfor  %}

</tbody>                
</table>
{%  endblock    %}

boards/templates/home1.html
{%  load    static  %}
<!DOCTYPE html> 
<html>        
<head>              
<meta   charset="utf-8">                
<title>Boards</title>               
<link   rel="stylesheet"    href="{%    static  'css/bootstrap.min.css'    %}">
</head>

<body>              
<h1>Boards</h1>
<table  border="1">                     
<thead>                             
<tr>                                        
<th>Board</th>                                      
<th>Posts</th>                                      
<th>Topics</th>                                     
<th>Last    Post</th>                               
</tr>                       
</thead>  

<tbody> 
{%  for board   in  boards  %}
<tr>
    <td><a  href="{%    url 'board_topics'  board.pk    %}">{{  board.name }}</a>  <br>   
<small class="text-muted d-block" style="color:#888">{{board.description}}</small>
    </td>
        <td class="align-middle">0</td>                                              
        <td class="align-middle">0</td>                                              
        <td></td>                                       
</tr>
{%  endfor  %}

</tbody>                
</table>
</body> 

</html>

boards/templates/includes/form.html
{%  load    widget_tweaks   %}
{%  for field   in  form    %}      
<div    class="form-group">             
    {{  field.label_tag }}
    {%  if  form.is_bound   %}                      
    {%  if  field.errors    %}                              
        {%  render_field    field   class="form-control is-invalid" %}                       
    {%  for error   in  field.errors    %}  
        <div    class="invalid-feedback">
        {{  error   }}                                      
        </div>                              
    {%  endfor  %}                      
    {%  else    %}                              
        {%  render_field    field   class="form-control is-valid"   % }
    {%  endif   %}              
    {%  else    %}                      
        {%  render_field    field   class="form-control"    %}
    {%  endif   %}
    {%  if  field.help_text %}                      
        <small  class="form-text    text-muted">
        <!-- {{  field.help_text }}    -->

            {{  field.help_text|safe    }}                  
        </small>                
    {%  endif   %}      
</div> {%   endfor  %}

boards/templates/new_topic.html
{%  extends 'base.html' %}
{%  load    widget_tweaks   %}

{%  block   title   %}
Start a   New Topic
{% endblock    %}
{%  block   breadcrumb  %}      
<li class="breadcrumb-item">
<a  href="{%    url 'home'  %}">Boards</a>
</li>        
<li class="breadcrumb-item">
<a  href="{%    url 'board_topics'  board.pk    %}">
{{  board.name  }}
</a>
</li>     
<li class="breadcrumb-item  active">New topic</li>
{%   endblock    %}
{%  block   content %}
    <form   method="post" novalidate>             
     {%  csrf_token  %}  
        {%  include 'includes/form.html'    %}  
<!--         {%  for field   in  form    %}
              <div    class="form-group">                             
            {{  field.label_tag }}

        {%  if  form.is_bound   %}                              
        {%  if  field.errors    %}
            {%  render_field    field   class="form-control is-invalid"    %}
        {%  for error   in  field.errors    %}
            <div    class="invalid-feedback">
           {{  error   }} 
            </div>                                      
        {%  endfor  %}
        {%  else    %}
            {%  render_field    field   class="form-control is-valid"    %}
        {%  endif   %}                      
        {%  else    %}                              
            {%  render_field    field   class="form-control"    %}
        {%  endif   %}

            {%  if  field.help_text %}             
             <small  class="form-text    text-muted"> 
            {{  field.help_text }} 
             </small>                                
            {%  endif   %}                      
            </div>              
        {%  endfor  %} -->
    
     <!-- {{ form.as_p   }}               -->
     <button type="submit"   class="btn  btn-success">Post</button >
      <!-- <div    class="form-group">                    
           <label  for="id_subject">Subject</label>      
           <input  type="text" class="form-control"    id="id_subject" name="subject">             
       </div>              
       <div    class="form-group">                    
            <label  for="id_message">Message</label>                        
            <textarea   class="form-control"    id="id_message" name="message" rows="5"></textarea>
        </div> 
        <button type="submit"   class="btn  btn-success">Post</button >    
     -->
     </form>
{%  endblock    %}

boards/templates/signup.html
{%  extends 'base.html' %}
{%  load    static  %}
{%  block   stylesheet  %}  
    <link   rel="stylesheet"    href="{%    static  'css/accounts.css'  % }">
{%  endblock    %}

{%  block   body %}      
        <div    class="container"> 
        <h1 class="text-center  logo    my-4">                      
        <a  href="{%    url 'home'  %}">Django  Boards</a>              
        </h1>               
        <div    class="row  justify-content-center">  
        <div    class="col-lg-8 col-md-10   col-sm-12">
        <div    class="card">                                     
        <div    class="card-body">                                              
        <h3 class="card-title">Sign up</h3>  

        <form   method="post"   novalidate>                     
            {%  csrf_token  %}                      
            <!-- {{  form.as_p   }}  --> 
               {%   include 'includes/form.html'    %}                 
            <button type="submit"   class="btn  btn-primary">Create an  account</button>                
        </form>     
            </div>                                      
            <div    class="card-footer  text-muted  text-center"> Already have    an  account?    
            <a  href="#">Log    in</a> 
            </div>                              
            </div>                      
            </div>              
            </div>      
            </div> 
{%  endblock body  %}

boards/templates/topics.html
{%  extends 'base.html' %}
{%  block   title   %}      
{{  board.name  }}  -   {{  block.super }}
 {%   endblock    %}

{%  block   breadcrumb  %}  
<li class="breadcrumb-item"><a  href="{%    url 'home'  %}" >Boards</a></li>
<li class="breadcrumb-item  active">{{  board.name  }}</ li>
 {%   endblock    %}

{%  block   content %}  
<div    class="mb-4">               
<a  href="{%    url 'new_topic' board.pk    %}" class="btn  btn-p rimary">New   topic</a>
</div>            
<!--    just    leaving it  empty   for now.    we  will    add core    here    soon.   --> 
    <table  class="table">              
    <thead  class="thead-inverse">                      
    <tr>                                
        <th>Topic</th>                              
        <th>Starter</th>                                
        <th>Replies</th>                                
        <th>Views</th>                              
        <th>Last    Update</th>  
        <th>Emails</th>                              
                   
    </tr>               

    </thead>                
    <tbody>                     
    {%  for topic   in  board.topics.all    %} 
    <tr>                                        
        <td>{{  topic.subject   }}</td>   
        <td>{{  topic.starter.username  }}</td> 
        <td>0</td>                                      
        <td>0</td>                                      
        <td>{{  topic.last_updated  }}</td>  
        <td>{{  topic.starter.email  }}</td> 

    </tr>                       
    {%  endfor  %}              
    </tbody>        
    </table>
{%  endblock    %}

boards/templates/topics1.html
{%  load    static  %}
<!DOCTYPE html> 
<html>        
<head>              
<meta   charset="utf-8">                
<title>{{   board.name  }}</title>              
<link   rel="stylesheet"    href="{%    static  'css/bootstrap.min.css'    %}">        
</head>     

<body>              
<div    class="container">  

<ol class="breadcrumb   my-4">                              
<li class="breadcrumb-item"><a  href="{%    url 'home'  %}" >Boards</a></li>
<li class="breadcrumb-item  active">{{  board.name  }}</ li>
</ol>   

</div>      
</body> 
</html>